config/routes.rb
Rails.application.routes.draw do
  resources :dashing_d3_examples
  resources :user_stories
  resources :action_items
  resources :projects

    root 'dashing_d3_examples#index'

    get '/arrays', to: 'dashing_d3_examples#arrays'  
    get '/adding_dom_elements',to: 'dashing_d3_examples#adding_dom_elements'
    get '/svg_fundamentals',to: 'dashing_d3_examples#svg_fundamentals'
    get '/adding_svg_elements',to: 'dashing_d3_examples#adding_svg_elements'
    get '/data_operator',to: 'dashing_d3_examples#data_operator'
    get '/javascript_functions',to: 'dashing_d3_examples#javascript_functions'
    get '/using_data_bound_to_dom',to: 'dashing_d3_examples#using_data_bound_to_dom'
    get '/svg_elements_from_data',to: 'dashing_d3_examples#svg_elements_from_data'
    get '/using_svg_coordinate_space',to: 'dashing_d3_examples#using_svg_coordinate_space'
    get '/json_intro',to: 'dashing_d3_examples#json_intro'
    get '/d3_start_fiddle',to: 'action_items#d3_start_fiddle'
    get '/json_basic_shapes',to: 'dashing_d3_examples#json_basic_shapes'
    get '/svg_json_paths',to: 'dashing_d3_examples#svg_json_paths'
    get '/dynamic_svg_coordinate_space',to: 'dashing_d3_examples#dynamic_svg_coordinate_space'
    get '/d3_scales',to: 'dashing_d3_examples#d3_scales'
    get '/svg_group_element',to: 'dashing_d3_examples#svg_group_element'
    get '/svg_text_elements',to: 'dashing_d3_examples#svg_text_elements'
    get '/margin_convention',to: 'dashing_d3_examples#margin_convention'
    get '/dates_and_times',to: 'dashing_d3_examples#dates_and_times'
    get '/d3_axes',to: 'dashing_d3_examples#d3_axes'
    get '/axes_manipulation',to: 'dashing_d3_examples#axes_manipulation'
    get '/scales_for_data',to: 'dashing_d3_examples#scales_for_data'
    get '/first_half_together',to: 'dashing_d3_examples#first_half_together'
    get '/basic_line_chart',to: 'dashing_d3_examples#basic_line_chart'
    get '/basic_bar_chart',to: 'dashing_d3_examples#basic_bar_chart'
    get '/negative_bar_chart',to: 'dashing_d3_examples#negative_bar_chart'
    get '/basic_area_chart',to: 'dashing_d3_examples#basic_area_chart' 
    get '/basic_grouped_bar_chart', to: 'dashing_d3_examples#basic_grouped_bar_chart'
     

      get 'all_actions' => 'action_items#all_actions'

  

end

app/models/user_story.rb
class UserStory < ActiveRecord::Base
end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  before_action :set_user_story, only: [:show, :edit, :update, :destroy]

  # GET /user_stories
  # GET /user_stories.json
  def index
    @user_stories = UserStory.all
  end

  # GET /user_stories/1
  # GET /user_stories/1.json
  def show
  end

  # GET /user_stories/new
  def new
    @user_story = UserStory.new
  end

  # GET /user_stories/1/edit
  def edit
  end

  # POST /user_stories
  # POST /user_stories.json
  def create
    @user_story = UserStory.new(user_story_params)

    respond_to do |format|
      if @user_story.save
        format.html { redirect_to @user_story, notice: 'User story was successfully created.' }
        format.json { render :show, status: :created, location: @user_story }
      else
        format.html { render :new }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stories/1
  # PATCH/PUT /user_stories/1.json
  def update
    respond_to do |format|
      if @user_story.update(user_story_params)
        format.html { redirect_to @user_story, notice: 'User story was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_story }
      else
        format.html { render :edit }
        format.json { render json: @user_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stories/1
  # DELETE /user_stories/1.json
  def destroy
    @user_story.destroy
    respond_to do |format|
      format.html { redirect_to user_stories_url, notice: 'User story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_story
      @user_story = UserStory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_story_params
      params.require(:user_story).permit(:title, :content, :user_id)
    end
end

app/helpers/user_stories_helper.rb
module UserStoriesHelper
end

app/views/user_stories/_form.html.erb
<%= form_for(@user_story) do |f| %>
  <% if @user_story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_story.errors.count, "error") %> prohibited this user_story from being saved:</h2>

      <ul>
      <% @user_story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_stories/edit.html.erb
<h1>Editing User Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_story %> |
<%= link_to 'Back', user_stories_path %>

app/views/user_stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Stories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_stories.each do |user_story| %>
      <tr>
        <td><%= user_story.title %></td>
        <td><%= user_story.content %></td>
        <td><%= user_story.user_id %></td>
        <td><%= link_to 'Show', user_story %></td>
        <td><%= link_to 'Edit', edit_user_story_path(user_story) %></td>
        <td><%= link_to 'Destroy', user_story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User story', new_user_story_path %>

app/views/user_stories/new.html.erb
<h1>New User Story</h1>

<%= render 'form' %>

<%= link_to 'Back', user_stories_path %>

app/views/user_stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @user_story.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @user_story.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_story.user_id %>
</p>

<%= link_to 'Edit', edit_user_story_path(@user_story) %> |
<%= link_to 'Back', user_stories_path %>