config/routes.rb
Rails.application.routes.draw do
  resources :dashing_d3_examples
  resources :user_stories
  resources :action_items
  resources :projects

    root 'dashing_d3_examples#index'

    get '/arrays', to: 'dashing_d3_examples#arrays'  
    get '/adding_dom_elements',to: 'dashing_d3_examples#adding_dom_elements'
    get '/svg_fundamentals',to: 'dashing_d3_examples#svg_fundamentals'
    get '/adding_svg_elements',to: 'dashing_d3_examples#adding_svg_elements'
    get '/data_operator',to: 'dashing_d3_examples#data_operator'
    get '/javascript_functions',to: 'dashing_d3_examples#javascript_functions'
    get '/using_data_bound_to_dom',to: 'dashing_d3_examples#using_data_bound_to_dom'
    get '/svg_elements_from_data',to: 'dashing_d3_examples#svg_elements_from_data'
    get '/using_svg_coordinate_space',to: 'dashing_d3_examples#using_svg_coordinate_space'
    get '/json_intro',to: 'dashing_d3_examples#json_intro'
    get '/d3_start_fiddle',to: 'action_items#d3_start_fiddle'
    get '/json_basic_shapes',to: 'dashing_d3_examples#json_basic_shapes'
    get '/svg_json_paths',to: 'dashing_d3_examples#svg_json_paths'
    get '/dynamic_svg_coordinate_space',to: 'dashing_d3_examples#dynamic_svg_coordinate_space'
    get '/d3_scales',to: 'dashing_d3_examples#d3_scales'
    get '/svg_group_element',to: 'dashing_d3_examples#svg_group_element'
    get '/svg_text_elements',to: 'dashing_d3_examples#svg_text_elements'
    get '/margin_convention',to: 'dashing_d3_examples#margin_convention'
    get '/dates_and_times',to: 'dashing_d3_examples#dates_and_times'
    get '/d3_axes',to: 'dashing_d3_examples#d3_axes'
    get '/axes_manipulation',to: 'dashing_d3_examples#axes_manipulation'
    get '/scales_for_data',to: 'dashing_d3_examples#scales_for_data'
    get '/first_half_together',to: 'dashing_d3_examples#first_half_together'
    get '/basic_line_chart',to: 'dashing_d3_examples#basic_line_chart'
    get '/basic_bar_chart',to: 'dashing_d3_examples#basic_bar_chart'
    get '/negative_bar_chart',to: 'dashing_d3_examples#negative_bar_chart'
    get '/basic_area_chart',to: 'dashing_d3_examples#basic_area_chart' 
    get '/basic_grouped_bar_chart', to: 'dashing_d3_examples#basic_grouped_bar_chart'
     

      get 'all_actions' => 'action_items#all_actions'

  

end

app/models/action_item.rb
class ActionItem < ActiveRecord::Base
scope :randActionItem, -> { limit(3).order("random()")} 


  belongs_to :project
  before_create :create_action_number
  after_create :total_update
  def create_action_number
    self.action_number = project.total_actions if project
  end
  def total_update
  	project.total_actions_update if project
  end
end

app/controllers/action_items_controller.rb
class ActionItemsController < ApplicationController
  before_action :set_action_item, only: [:show, :edit, :update, :destroy]

  # GET /action_items
  # GET /action_items.json
  def index
    @action_items = ActionItem.all
    @projects = Project.all
    @action_info = ActionItem.all.select(:id, :action_number,:total_action)
    #render json: @action_info
  end

  # GET /action_items/1
  # GET /action_items/1.json
  def show
    @action_items = ActionItem.find(params[:id])

    #@action_items = ActionItem.where(accession_number: params[:accession_number])
  end

  def show_all_actions
    @action_item.where(accession_number: params[:accession_number])
  end

  def actions

  end
  # GET /action_items/new
  def new
    @projects = Project.all 
    @action_item = ActionItem.new
  end

  # GET /action_items/1/edit
  def edit
  end

  # POST /action_items
  # POST /action_items.json
  def create
    @action_item = ActionItem.new(action_item_params)

    respond_to do |format|
      if @action_item.save
        format.html { redirect_to @action_item, notice: 'Action item was successfully created.' }
        format.json { render :show, status: :created, location: @action_item }
      else
        format.html { render :new }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_items/1
  # PATCH/PUT /action_items/1.json
  def update
    respond_to do |format|
      if @action_item.update(action_item_params)
        format.html { redirect_to @action_item, notice: 'Action item was successfully updated.' }
        format.json { render :show, status: :ok, location: @action_item }
      else
        format.html { render :edit }
        format.json { render json: @action_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_items/1
  # DELETE /action_items/1.json
  def destroy
    @action_item.destroy
    respond_to do |format|
      format.html { redirect_to action_items_url, notice: 'Action item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def d3_start_fiddle
    @action_info = ActionItem.all.select(:id, :accession_number,:action_number,:total_action,:created_at)
    @randAct = ActionItem.randActionItem 
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_action_item
      @action_item = ActionItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def action_item_params
      params.require(:action_item).permit(:accession_number, :description, :action_number, :project_id)
    end
end

app/helpers/action_items_helper.rb
module ActionItemsHelper
end

app/views/action_items/_form.html.erb
<%= form_for(@action_item) do |f| %>
  <% if @action_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@action_item.errors.count, "error") %> prohibited this action_item from being saved:</h2>

      <ul>
      <% @action_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
  <%= f.label :accession_number %><br>
  <% options = options_from_collection_for_select(@projects, 'accession_number', 'accession_number') %>
<%= f.select :accession_number,  options %>
</div>

  <div class="field">
    <%= f.label :project_id %><br>
    <% options = options_from_collection_for_select(@projects,'id','title') %>
    <%= f.select :project_id,  options %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/action_items/all_actions.html.erb
<h1> hw</h1>

app/views/action_items/all_actions_for_accession_number.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accession number:</strong>
  <%= @action_item.accession_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @action_item.description %>
</p>

<p>
  <strong>Action number:</strong>
  <%= @action_item.action_number %>
</p>

<p>
  <strong>Project:</strong>
  <%= Project.find(@action_item.project) %>
</p>

<%= link_to 'Edit', edit_action_item_path(@action_item) %> |
<%= link_to 'Back', action_items_path %>

app/views/action_items/d3_start_fiddle.html.erb
<html>
<head>
</head>
<body>
	<h1>The data:</h1>
	<div class="scopedVar"><%= @randAct.to_json %></div>
	<div class="manipulateJson"></div>
	<div class="visualizeRect"></div>
	
</body>
<script>
//d3.select("body").remove("svg");
var svgContainer = d3.select("body").select(".visualizeRect").append("svg").attr("width","1000").attr("height","10000");

var rectangles = <%=raw  @action_info.to_json%>;
var svgRectangles = svgContainer.selectAll("rect").data(rectangles).enter().append("rect");
svgRectangles.attr("x", function(d,i){return d.id * 3 ;})
					.attr("y", function(d,i){return d.action_number * i ;})
					.attr("width", function(d,i){return d.total_action;})
					.attr("height", function(d,i){return d.accession_number*10;})
					;
					//.style("fill", function(d,i){return d.fill;});
</script>

</html>

app/views/action_items/edit.html.erb
<h1>Editing Action Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @action_item %> |
<%= link_to 'Back', action_items_path %>

app/views/action_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Action Items</h1>

<table>
  <thead>
    <tr>
      <th>Accession number</th>
      <th>Description</th>
      <th>Action number</th>
      <th>Total Actions</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @action_items.each do |action_item| %>
      <tr>
        <td><%= action_item.accession_number %></td>
        <td><%= action_item.description %></td>
        <td><%= action_item.action_number %></td>
        <td><%= action_item.total_action %></td>
        <td><%= action_item.project %></td>
        <td><%= link_to 'Show', action_item %></td>
        <td><%= link_to 'Edit', edit_action_item_path(action_item) %></td>
        <td><%= link_to 'Destroy', action_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% @projects.each do |p| %>
	<p><%=p.title%></p>
<% end -%>

<div>
<%= @action_info.to_json %>
</div>
<br>
<div id="svgHere"></div>
<%= link_to 'New Action item', new_action_item_path %>

app/views/action_items/new.html.erb
<h1>New Action Item</h1>

<%= render 'form' %>

<%= link_to 'Back', action_items_path %>

app/views/action_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accession number:</strong>
  <%= @action_item.accession_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @action_item.description %>
</p>

<p>
  <strong>Action number:</strong>
  <%= @action_item.action_number %>
</p>

<p>
  <strong>Project:</strong>
  <%= Project.find(@action_item.project) %>
</p>

<%= link_to 'Edit', edit_action_item_path(@action_item) %> |
<%= link_to 'Back', action_items_path %>